# Generated by Django 5.2.4 on 2025-07-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteria',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
    ]
