name: Django Backend CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    testes-backend:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                ports: ["5432:5432"]
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        env:
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
            DJANGO_SETTINGS_MODULE: paris_cafe.settings
            PYTHONUNBUFFERED: 1

        steps:
            - name: Checkout o código
              uses: actions/checkout@v4

            - name: Instalar Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Instalar dependências
              working-directory: paris_cafe
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Migrar banco de dados
              working-directory: paris_cafe
              run: |
                  python manage.py migrate

            - name: Executar testes com pytest
              working-directory: paris_cafe
              run: |
                  pytest --html=report.html

            - name: Upload do relatório de testes
              uses: actions/upload-artifact@v4
              with:
                  name: pytest-report
                  path: paris_cafe/report.html
